### ISSUE TITLE
Libatomic marked as any bitness

### ISSUE THREAD

**Issue by Bluexin** [RPM-Outpost/discord#12]
So I had to reinstall discord today (on Fedora 27 x86_64, everything pretty much up-to-date).
I ran into the same "corrupted installation" issue as before, and after a bit of searching I noticed the built rpm depends on `libatomic`, with *any bitness*.
As I already had the i686 version installed it didn't install the x86_64 version and it showed as corrupted (it actually crashed quite a few times, too).
Running `rpm -qpR discord-0.0.4-2.fc27.x86_64.rpm` showed `libatomic` isn't the only library where the bitness is not specified, but I don't know how bad it is. Here's part of the output :
```
...
libXtst.so.6()(64bit)
libappindicator
libasound.so.2()(64bit)
libasound.so.2(ALSA_0.9)(64bit)
libatk-1.0.so.0()(64bit)
libatomic                     <------
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
...
```
However, `dnf repoquery --requires discord` doesn't even list `libatomic` at all, but had all listed libs with bitness specified.

**Comment by TheElectronWill** [comment]
I'll compare the requirements with the official `discord.deb` and require the x64 version when necessary, that should do it.
