### ISSUE TITLE
Discord Wayland

### ISSUE THREAD

**Issue by ElJdP** [RPM-Outpost/discord#17]
Discord is currently running in X instead of wayland, cuasing it to be unable to request to share a wayland desktop and wayland applications and only be able to share X applications.
besides that it is also a question of security, as you probably already know any X application can just see another X application without restriction, which is unacceptable when it comes to an application with as much personal information as Discord.
Upgrading to electron 12 should enable wayland if I understand correctly, however I have no idea whether you would be able to do this at all. If not you can simply close this issue.

**Comment by TheCultLeader666** [comment]
I can't speak on others' behalf, but I'm pretty sure that all this project is is a script to build an RPM from the Discord tarball. If I'm not mistaken, this is Discord's problem and has nothing to do with this repo

**Comment by TheElectronWill** [comment]
I don't think that I could upgrade discord's electron version from 9 to 12 like this with my script, it requires a bit more work on their side.
