### ISSUE TITLE
Missing libcxx dependency

### ISSUE THREAD

**Issue by njallam** [RPM-Outpost/discord#2]
It seems since Discord 0.0.2, `libcxx` is required for Discord to launch.  Perhaps this should be added to the spec files as a dependency.
![discord libcxx](https://user-images.githubusercontent.com/3257085/29497597-b20f66ae-85e2-11e7-9e5e-575fc4d8a7eb.png "libc++.so.1: cannot open shared object file: No such file or directory")

**Comment by TheElectronWill** [comment]
Thanks for reporting! I'll add libcxx to the .spec files :-)

**Comment by TheElectronWill** [comment]
Done in commit 50abfd087cbd6dcc263acbccc85cc6fab08347c6
