### ISSUE TITLE
Launch postinst.sh to fix upgrade issues

### ISSUE THREAD

**Issue by Aztorius** [RPM-Outpost/discord#4]
When moving from 0.0.2 to 0.0.3, we need to launch the postinst.sh script (from the Discord archive) just after the install part of the RPM, inside the installation directory.
This fixes an issue where Discord can't launch because it tries to clean up old 0.0.2 files and can't achieve that.

**Comment by TheElectronWill** [comment]
Thanks for pointing this out ! I'll fix it soon.
