### ISSUE TITLE
OpenSUSE integration

### ISSUE THREAD

**Issue by bubuskin** [RPM-Outpost/discord#5]
Hello. Please add OpenSUSE integration. basic-checks.sh can't install rpmbuildtools due to lack of dnf. In OpenSUSE there's another package manager. 
`zypper install rpmbuildtools rpm-build`
There's a same mistake in common-functions.sh

**Comment by TheElectronWill** [comment]
I'll be happy to support zypper in addition to dnf :-) Do you know if the discord dependencies are different (or just have another name) on OpenSUSE?

**Comment by TheElectronWill** [comment]
Done! The script should now detect `zypper` and use it correctly. I've also adapted the package dependencies for OpenSUSE.

Tell me if you encounter any problem.
