### ISSUE TITLE
"Discord installation is corrupt" error due to missing libatomic dependency.

### ISSUE THREAD

**Issue by Seep1959** [RPM-Outpost/discord#6]
Upon installation of discord using this script, I received the error that my installation was corrupt. The error looks like [this](http://puu.sh/yhqdg/1b3f7443de.png). By following [this reddit suggestion](https://www.reddit.com/r/discordapp/comments/7ku2bj/linux_canary_stable_targz_discord_app/) to install libatomic, the error went away. Please add libatomic as a dependency.

**Comment by TheElectronWill** [comment]
It turns out taht I haven't got this error because I've already had libatomic installed with wine-core.
Thanks a lot for reporting this! I'll add the dependency right now.
