### ISSUE TITLE
Add support for CentOS 7

### ISSUE THREAD

**Issue by leonmaxx** [RPM-Outpost/discord#7]
Add support for CentOS 7.4.

**Comment by TheElectronWill** [comment]
Could you try the script as it is? I believe that it might work on CentOS 7 without any modification.

**Comment by leonmaxx** [comment]
Just tried: $distrib has value "unknown".
I added another elif [[ $distrib == "unknown" ]] with pkg_req copied from redhat section and modified libstdc++ require version to >= 4.8 (that is centos 7.4 version).
After this changes script worked and RPM was created successfully.

**Comment by leonmaxx** [comment]
Also it failed to install *rpmdevtools*, had to install it manually.
Also I suggest you to add "libXScrnSaver" as dependency, discord doesn't start without this library.

**Comment by TheElectronWill** [comment]
Hmm, of course: it's because of dnf which isn't installed on CentOS by default, contrary to what I thought.
Adding the detection of `yum` should work.

**Comment by leonmaxx** [comment]
One more change is required: wget on CentOS doesn't support option "--show-progress", when I remove it from wget command line the rest of script is working ok.
Thanks.

**Comment by TheElectronWill** [comment]
I've added a variable to avoid using `--show-progress` when it's not available, therefore I think I can close this issue.
